### ISSUE TITLE
FR: Migrate to typescript

### ISSUE THREAD

**Issue by mamichels** [MasterIV/tin-engine#1]
Since this module is being used as framework, it should be fully typed on all exposed apis. In utmost humbleness I suggest a rework in typescript.

**Comment by MasterIV** [comment]
After carefully surveying our user base, we have concluded there is not demand for this kind of feature at the current time. Users have been comfortable with the framework in it's current state. But we might reconsider the issue in future, should our user-base grow noticeably.
